[project]
name = "pptx-editing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosmtplib>=5.0.0",
    "fastapi>=0.121.1",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pydantic[email]>=2.12.4",
    "python-dotenv>=1.1.1",
    "python-pptx>=1.0.2",
    "uvicorn>=0.38.0",
]
